---
name: Comandos de shell
on: #[push]
  schedule:
  - cron:"0/3 * * * *"
jobs: 
  ejecutar-comandos-shell:    
    runs-on: ubuntu-latest
    steps:      
      - name: step1
        run: echo "Hello World"
      - name: step2
        run: |
          node -v
          npm -v
          ls -la
          cat /etc/os-release
      - name: step3
        run: |
          import platform
          print(platform.processor())
        shell: python
  comandos-windows:
    runs-on: windows-latest
    steps:
      - name: step1
        run: Get-Location
      - name: step2
        run: pwd
        shell: bash
