---
name: Comandos de shell
on: [push]
jobs: 
  ejecutar-comandos-shell:    
    runs-on: ubuntu-latest
    steps:      
      - name: nombre step1
        run: echo "Hello World"
      - name: nombre step2
        run: |
          node-v
          npm-v
          ls -la
          cat /etc/os-release
